import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
tab = np.linspace(-5, 10, 1000)
X = stats.uniform.pdf(tab, -5, 7)
Y = stats.uniform.pdf(tab, 0, 4)
Z = stats.uniform.pdf(tab, -2, 4)
X_rep = stats.uniform.cdf(tab, -5, 7)
Y_rep = stats.uniform.cdf(tab, 0, 4)
Z_rep = stats.uniform.cdf(tab, -2, 4)
plt.plot(tab, X)
plt.plot(tab, Y)
plt.plot(tab, Z)
plt.show()
# rep
plt.plot(tab, X_rep)
plt.plot(tab, Y_rep)
plt.plot(tab, Z_rep)
plt.show()
X = stats.uniform.rvs(-5, 7, size = 1000)
Y = stats.uniform.rvs(0, 4, size = 1000)
Z = stats.uniform.rvs(-2, 4, size = 1000)
plt.hist(X, bins = 200)
plt.hist(Y, bins = 200)
plt.hist(Z, bins = 200)
plt.show()
print("X :")
print(stats.uniform.mean(loc=-5, scale=7))
print(stats.uniform.var(loc=-5, scale=7))
print("Y : ")
print(stats.uniform.mean(loc=0, scale=4))
print(stats.uniform.var(loc=0, scale=4))
print("Z : ")
print(stats.uniform.mean(loc=-2, scale=4))
print(stats.uniform.var(loc=-2, scale=4))